### ISSUE TITLE
Link Breakage

### ISSUE THREAD

**Issue by alexamorris** [ghwood/www.ietf.org#12]
## URL

https://www7.ietf.org/how-we-work/meetings/past/96/register-next-ietf-meeting/
## Expected Behavior

I moved IETF 96 to Past Meetings. I expected the links on the IETF 96 page to continue to function. 
## Actual Behavior

While the link to "Register" worked as expected prior to the move to the Past Meetings folder, once IETF 96 was in the Past Meetings folder the Register link no longer takes the user anywhere at all -- it seems to refresh the IETF 96 start page. 
## Reproducing
- Browser: Chrome
- OS: 10.9.5
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
None of the links work for me in pages using the event template.

For example, the registration (or any) links in:

https://www7.ietf.org/how-we-work/meetings/97/

or

https://www7.ietf.org/how-we-work/meetings/past/94/

Could you test that to confirm it?

**Comment by ghwood** [comment]
This is an example of the Event template link problem, which has been consolidated into this ticket:

https://github.com/ietf/www.ietf.org/issues/15
