### ISSUE TITLE
Past Meetings

### ISSUE THREAD

**Issue by alexamorris** [ghwood/www.ietf.org#13]
## URL

Multiple URLs, in fact all Past Meetings that we looked. Example: https://www7.ietf.org/how-we-work/meetings/past/ietf-84-vancouver/
## Expected Behavior

I expected that clicking on any of the submenu links would take the user to the new version of that designated page. 
## Actual Behavior

None of these sublinks seem to work. What happens is that the meeting start page (e.g. https://www7.ietf.org/how-we-work/meetings/past/ietf-84-vancouver/) is refreshed. Essentially there appears to be no content beyond the initial meeting start page. 
## Reproducing
- Browser: Chrome
- OS: 10.9.5
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
As noted in several other issues, this seems to be an issue with the Event Page template. I am asking for this to be confirmed here: https://github.com/ietf/www.ietf.org/issues/12 and will consolidate into a ticket for Torchbox to fix.

**Comment by ghwood** [comment]
This is an example of the Event template link problem, which has been consolidated into this ticket:

https://github.com/ietf/www.ietf.org/issues/15
