### ISSUE TITLE
Register for the Next IETF Meeting Weirdness

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#14]
## URL

http://www7.ietf.org/admin/pages/1057/edit/
http://www7.ietf.org/how-we-work/meetings/96/register-next-ietf-meeting/
## Expected Behavior

The content should look exactly like it does in the admin page
## Actual Behavior

The content on the live page has '\n' throughout the body. 
## Reproducing
- Browser: Chrome
- OS: 10.9.4

**Comment by akvezza** [comment]
Also seeing the \n added in to copied text from plain text documents. The link I see this on is:

http://www7.ietf.org/how-we-work/meetings/interim-meetings/ntp-wg-interim-meeting-october-14-2016-boston-ma-usa/

My browser is Firefox
Mac OS 10.10.5

**Comment by ghwood** [comment]
The issue of extraneous text has been fixed.
