### ISSUE TITLE
Events Pages Links - All Meetings

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#15]
## URL

http://www7.ietf.org/admin/pages/27/edit/
http://www7.ietf.org/how-we-work/meetings/ietf95/
## Expected Behavior

Everything under key details (Additional Meetings, General etc) in the admin area should be linking to the live IETF 95 Meeting Page.
## Actual Behavior

None of the links entered in the admin area (for example under Key Details -> General -> Register should link to the internal page 'Register for the Next Meeting' however on the live page the link is http://www7.ietf.org/how-we-work/meetings/ietf95/. This is the case for every link on every event page (for all past and current IETF meetings)
## Reproducing
- Browser: Chrome
- OS: 10.9.4
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
A ticket has been filed with Torchbox. I will advise regarding resolution. Other tickets here reporting the same basic Event template/link bug have been pointed here.

**Comment by ghwood** [comment]
This issue seems to have been fixed, so closing the ticket.
