### ISSUE TITLE
Link issue in Admin Area

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#17]
## URL

http://www7.ietf.org/admin/pages/1060/edit/
## Expected Behavior

In the Key Info section, I would expect you to be able to hover over the highlighted words (for example here and IETF Companions Facebook Page) and see what those are linked to and edit them or to click the link button in the tool bar and have the ability to edit it.
## Actual Behavior

 If you press the link button it removes the link instead of giving you information about it.
## Reproducing
- Browser: Chrome
- OS: 10.9.4
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
This would require a feature addition in the Wagtail editing interface. I've flagged this as an enhancement for possible action in the next round of development.

**Comment by flynnliz** [comment]
Can I second this issue? This feature makes editing extremely difficult since it's impossible to tell where links go. can it be bumped up in priority if possible?

**Comment by ghwood** [comment]
I actually think this is a general request for any link in the editing interface. That is, it is not just in the "Key Info" section. Is that correct, @macmccammon ?

**Comment by ghwood** [comment]
I think this has been addressed so am closing the ticket.
