### ISSUE TITLE
Broken links in page footers

### ISSUE THREAD

**Issue by cindymorgan** [ghwood/www.ietf.org#18]
## URL

https://www7.ietf.org (and all pages with the normal template footer)
## Expected Behavior

I expected the "Tools Team", "Datatracker" etc links to point to those pages.
## Actual Behavior

All of the links in the footer seem to use href="#" and so just point back to the page you're already on.
## Reproducing
- Browser: Firefox 48.0.1
- OS: MacOS 10.10.5
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
These links (including which links) can be specified and will be edited by Torchbox. We need to confirm which links these should be.

**Comment by ghwood** [comment]
These are fixed.
