### ISSUE TITLE
Unusable Page - IETF 96 Hotel

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#19]
## URL

http://www7.ietf.org/how-we-work/meetings/past/96/meeting-venue-and-hotels/
## Expected Behavior

I had the expectation that when the content was copied over it would be in a usable format for the community. 
## Actual Behavior

This page is not usable. Section anchors connect back to the old website (and I thought the new website would not have section anchors to begin with), the content is impossible to navigate and there are bad characters throughout. It appears that there is also html in the backend, and I'm curious if we are able to replicate that on our own.
## Reproducing
- Browser: Chrome
- OS: 10.9.4
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
Chris: can you look into seeing if you can fix this?

**Comment by ChrisDart** [comment]
OK looking into it.

**Comment by ChrisDart** [comment]
The issue with things linking back to the old site was just an oversight on my end, and can totally be fixed by converting things to when I bring them over from the old site. I'll keep an eye on it.

The other, bigger issue of all those bad characters is a child of Issue No. 8 (https://github.com/ietf/www.ietf.org/issues/8) that we flagged at the end of August and is currently with Torchbox.

**Comment by ghwood** [comment]
Chris,

A proposed fix for the extra characters resulting from copy/paste developed by Torchbox has been deployed on the Wagtail site that _should_ work for new content, but I’m afraid it won’t clean up existing content. Would you mind trying to rebuild the "IETF 96 - Meeting Venue and Hotels” page (https://www.ietf.org/meeting/96/hotel.html) as a test?

-Greg

**Comment by ChrisDart** [comment]
Hey Greg,

This seemed to work for this page for everything except the tables. Were we just going to deep six tables anyway?

**Comment by ghwood** [comment]
Chris,

I think we were going to keep the tables using the “Raw HTML” feature in Wagtail. Let me know if you’d like to discuss.

-Greg

**Comment by ghwood** [comment]
I believe this issue has now been fixed.
