### ISSUE TITLE
All page links go back to page you are on even if other links are added

### ISSUE THREAD

**Issue by akvezza** [ghwood/www.ietf.org#20]
## URL

http://www7.ietf.org/how-we-work/working-groups/working-group-chair-resources/
## Expected Behavior

I expect all the links to go to where the link says it goes to. You can see where the link is assigned to go on the edit page, but that doesn't appear in the live version.
## Actual Behavior

I expect all the links that have been added as links on this page are showing up as this URL on the live version, even if the link has been filled in to an external page

<img width="860" alt="wagtail-example" src="https://cloud.githubusercontent.com/assets/22179253/18970936/3ca89b46-8661-11e6-9f19-70c60083a568.png">

This link does not appear to be live on the site. The "link" when you click on it is for the page it is on. It doesn't GO anywhere.  ALL of the links on this page are the same.
## Reproducing
- Browser: Firefox 49.0
- OS: MAC X (10.10.5)
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
As noted in several other issues, this seems to be an issue with the Event Page template. I am asking for this to be confirmed here: https://github.com/ietf/www.ietf.org/issues/12 and will consolidate into a ticket for Torchbox to fix.

**Comment by ghwood** [comment]
This is an example of the Event template link problem, which has been consolidated into this ticket:

https://github.com/ietf/www.ietf.org/issues/15
