### ISSUE TITLE
Editing Hyperlinks Produces Extraneous Characters

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#25]
## URL

https://www7.ietf.org/how-we-work/meetings/past/93/ietf-93-tutorials/

## Expected Behavior

To edit hyperlinks with no change to the formatting or text.

## Actual Behavior

Hyperlinks updated to point to correct pages will sometimes produce the extraneous "/n" characters.  The cause is unknown, and further confused by the fact that editing hyperlinks on some pages that should be identical produce no errors (eg. https://www7.ietf.org/how-we-work/meetings/past/94/tutorials/ ) 

## Reproducing

- Browser: Chrome Version 54.0.2840.71 m (64-bit)
- OS: Windows 10 Home Edition

**Comment by ghwood** [comment]
I believe this is now fixed. See Ticket https://github.com/ietf/www.ietf.org/issues/8
