### ISSUE TITLE
Extraneous Â Appearing In Some Published Text

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#26]
## URL

https://www7.ietf.org/how/meetings/past/92/tutorials/ 
https://www7.ietf.org/how/meetings/97/ietf-97-local-letters-invitation/ 
https://www7.ietf.org/how/meetings/97/thursday-speaker-series/

## Expected Behavior

The pages should publish normally.

## Actual Behavior

Pages randomly include Â within the text.

![1df33e68c98d0b6584be0a2313da60e3](https://cloud.githubusercontent.com/assets/21247075/20324907/5dfbda92-ab50-11e6-9c84-ca04467ed4fd.png)

## Reproducing

- Browser: Firefox 49.0.2
- OS: Windows 10 Home Edition

**Comment by ghwood** [comment]
has been addressed in all found issues. continue to review and monitor top 100 pages
