### ISSUE TITLE
IETF Blog Sidebar Menu Not Scaling in Firefox - Unreadable

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#28]
## URL

https://www7.ietf.org/blog/iesg-and-chair-report-ietf-97/

## Expected Behavior

The sidebar link menu on the IETF Blog should scale to the right to make room for the blog post text.  It does this in Chrome, eg.:
![chrome](https://cloud.githubusercontent.com/assets/21247075/20326417/b4e7b780-ab56-11e6-80cb-7969b0ad5bb4.png)

## Actual Behavior

Viewing from Firefox, the menu does not scale, and takes up more than 50% of the page regardless of the window size.

![firefox](https://cloud.githubusercontent.com/assets/21247075/20326436/cbdc388a-ab56-11e6-91b6-aa660dee8d69.png)

## Reproducing

- Browser: Firefox 49.0.2
- OS: Windows 10

**Comment by ghwood** [comment]
I've reproduced this issue and passed it along to Torchbox via Codebase ticket for action.

**Comment by ghwood** [comment]
This issue has been resolved on www7.ietf.org
