### ISSUE TITLE
Embedded Images All Expand to Full Page Width

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#29]
## URL
https://www7.ietf.org/blog/welcome-ietf-97/?

## Expected Behavior

The images are inserted to align right and sit within the text, such as it does in the old blog: https://www.ietf.org/blog/2016/11/welcome-to-ietf-97/

## Actual Behavior

The images, no matter how they are inserted, blow up to the full width of the post.
![002d201de34422cb8d4831488ea395e1](https://cloud.githubusercontent.com/assets/21247075/20359928/dedd4ea2-abff-11e6-819d-73f412b47105.png)

## Reproducing

- Browser: Chrome 54.0.2840.99 but occurs in all browsers
- OS: Windows 10 Home Edition

**Comment by ghwood** [comment]
This is expected behavior for the Blog page template in Wagtail. I have documented this in the online content maintainer guide (https://docs.google.com/document/d/1jBrml8Ub9TJs_lXg831FivUkLKa4xav8sm2ArcwMNpI/edit)  so that blog posts going forward will include the proper image sizes:
