### ISSUE TITLE
ART Area description key info / in-depth needs edit

### ISSUE THREAD

**Issue by rjsparks** [ghwood/www.ietf.org#3]
## URL

https://www.ietf.org/areas/applications-and-real-time-area-art/
## Content Issue

Since the text for the key-info and the in-depth views never appear at the same time, the current text for the art area does not work. The ADs should be approached for a better description, and told of the need for a separate key-info banner.

**Comment by ghwood** [comment]
I think this has been addressed through a combination of template updates and content changes. The text here:

https://www7.ietf.org/topics/areas/art/

no mirrors the text here:

https://www.ietf.org/iesg/area.html

but of course can be updated as needed.
