### ISSUE TITLE
Links to IESG-Old?

### ISSUE THREAD

**Issue by cindymorgan** [ghwood/www.ietf.org#37]
## URL
http://www7.ietf.org/about/groups/
http://www7.ietf.org/about/groups/iesg-old/

## Expected Behavior

The Groups index page link to the IESG goes to the current IESG page.

## Actual Behavior

On the Groups index page, there is a link to http://www7.ietf.org/about/groups/iesg-old/, and then http://www7.ietf.org/about/groups/iesg-old/ has a bunch of child pages that appear to not actually exist. What happened to the non "old" version? At least one point, there was a non-old version, with non-old child pages.

## Reproducing

- Browser: Chrome 55.0.2883.95
- OS: Mac OS 10.10.5
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
This has been fixed.
