### ISSUE TITLE
Bulleted Lists displaying with too much space

### ISSUE THREAD

**Issue by macmccammon** [ghwood/www.ietf.org#43]
## URL

https://www7.ietf.org/how/runningcode/hackathons/

## Expected Behavior

The header for each hackathon should be much closer to the information regarding that hackathon in the bulleted list below it.

## Actual Behavior

It seems almost an entire line break is being added between the header and the bulleted list.

## Reproducing

- Browser:
- OS: Firefox 50.0.1
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
filed with Torchbox:

https://torchbox.codebasehq.com/projects/ietf/tickets/133

Here's the screenshot I included.
![screen shot 2017-06-13 at 4 06 46 pm](https://user-images.githubusercontent.com/5347540/27103362-5f68f148-5056-11e7-94b6-1fe5f81114f3.png)

**Comment by ghwood** [comment]
Updated style to reduce spacing, have bullets as close together as possible without allowing unintended vertical overlap of text.
