### ISSUE TITLE
Text formatting issues

### ISSUE THREAD

**Issue by navok89** [ghwood/www.ietf.org#54]
## URL

https://www7.ietf.org/how/meetings/important-dates/

## Expected Behavior

In the draft, part of the text is bolded. The text is supposed to show up as formatted in the backend.

## Actual Behavior

The text in the live version does not match the backend version. 

## Reproducing

- Browser:
- OS: [Operating System name] [Version]
- (anything else you think we might need to reproduce this)

**Comment by ghwood** [comment]
This has been filed as a bug with Torchbox:
https://torchbox.codebasehq.com/projects/ietf/tickets/136

**Comment by ghwood** [comment]
Hi Naveen, 

There's been quite a bit of hunting and testing. 

Could you share a screenshot of what you see here:

https://ietf-staging.torchboxapps.com/about/mission-and-principles/

And indicate which browser and operating system you are using? Also, whether you are using any ad blockers or other browser add-ons.

Thanks,
-Greg

**Comment by ghwood** [comment]
I think this either been fixed or OBE so closing the ticket.
