### ISSUE TITLE
Difficult to select from top menus

### ISSUE THREAD

**Issue by elear** [ghwood/www.ietf.org#57]
## URL

https://beta.ietf.org/

## Expected Behavior

When hovering over "Internet Standards" I should be able to transition down to the menu that includes "Standards Processes, RFCs, [etc]".  Only if I quickly jerk the mouse down do I get to the menu in time before it disappears.

## Actual Behavior

It is difficult to actually move the mouse down to the menu as it often disappears before I can make a selection.

## Reproducing

- Browser:

Firefox 54.0.1

- OS: [Operating System name] [Version]

MacOS 10.12.5

- (anything else you think we might need to reproduce this)

The problem definitely does NOT occur in Safari (just tested).

**Comment by ghwood** [comment]
I have just tested using the exact same browser/os combo on a couple of pages and don't observe the same behaviour. We'll investigate further.

**Comment by ghwood** [comment]
this looks to be working on several browsers tested, so closing the ticket.
