### ISSUE TITLE
NoScript warning wrt typekit.net

### ISSUE THREAD

**Issue by sftcd** [ghwood/www.ietf.org#58]
## URL

https://beta.ietf.org/

## Expected Behavior

Expect to not see a NoScript warning. With my noscript settings, allowing 
ietf.org, the beta site renders well other than this warning. I tried it without
allowing ietf.org and it's still good, thanks.

## Actual Behavior

NoScript still warns about typekit.net

## Reproducing

- Browser: FF latest
- OS: Ubuntu 17.04
- Install NoScript

**Comment by ghwood** [comment]
I have flagged this for the developers to check/address once the site is moved to www.ietf.org. It does depend on loading fonts, but I believe this will be resolved once the move is made--so closing this ticket.
