### ISSUE TITLE
area pages content doesn't give the right impression

### ISSUE THREAD

**Issue by sftcd** [ghwood/www.ietf.org#59]
## URL

https://beta.ietf.org/topics/areas/int/

## Expected Behavior

I'd expect to get an overview of the area and a list of current WGs, which is what seems to have been attempted, but it's not looking that good now IMO.

## Actual Behavior

Alphabetic ordering of WGs with each getting so much screen real estate means I don't get anywhere near the full list so may not find what I'm after. (Also we don't want an incentive to have new WGs start with an "A":-)

Presenting RFCs and drafts "belonging" to the area seems likely to mislead. We don't have many of those really, so I'd leave that out.

I'm missing the links to area lists and area wgs (e.g. dispatch, saag) and explanations of the different ways different areas deal with those. That last could be quite useful.

On the sec area page, somehow I'm still listed as an AD - you may have some bug there or maybe it's just a content issue, not sure.

## Reproducing

- Browser: FF and chromium
- OS: Ubuntu 17.04
- Issues are the same with/without JS turned on

**Comment by ghwood** [comment]
Thanks very much for the review. Yes, the content on the area pages is still a bit rough: we'll polish it with review and input from the relevant area directors before moving to production.

Good observation about the alphabetized listings...will consider how to address.

I see the same thing about you being listed as AD--and also that the role is incorrectly listed as "chair". That info should be directly from datatracker so will look into what's going on.

**Comment by ghwood** [comment]
The AD listing has been fixed, but we'll need to re-engineer the page templates (since they draw the information from datatracker) to address the WG, RFC, I-D, and mailing list listings. That's been added as a feature request.

Since we're moving away from this issue tracker and archiving it, I'm closing this ticket, but providing a pointer to it.
