### ISSUE TITLE
Test RFC Link Addition

### ISSUE THREAD

**Issue by ghwood** [ghwood/www.ietf.org#6]
## URL

Any page at https://www7.ietf.org/
## Expected Behavior

Add a link to RFC information from datatracker
## Actual Behavior

Link provided by dialogue box not selectable
## Reproducing
- Browser: Google Chrome
- OS: Mac OS X 10.11.6
  ![screen shot 2016-08-25 at 3 44 54 pm](https://cloud.githubusercontent.com/assets/5347540/17983502/e5804c48-6ada-11e6-9829-b1edbea80440.png)

**Comment by ChrisDart** [comment]
Confirm this is reproduced in Firefox 48.0.2 on Windows 10.

**Comment by ghwood** [comment]
Raised with Torchbox.

**Comment by ghwood** [comment]
This seems to be fixed. Asking @ChrisDart to confirm. If it is, we can close the ticket.

**Comment by ChrisDart** [comment]
I just had a look here and was still having problems. I clicked RFC link and got a page that looks like this.

![screen shot 2016-10-18 at 11 43 53 am](https://cloud.githubusercontent.com/assets/21247075/19485168/3be20906-9528-11e6-9b7c-438f500f7976.png)

In OSX, Safari 9.1.1

**Comment by ghwood** [comment]
I just tried this https://www7.ietf.org/about/mission-and-principles/ https://www7.ietf.org/about/mission-and-principles/

Relinking the “RFC 3935” text.

And it worked OK for me. See the screen shot attached.

-Greg
![screen shot 2016-10-18 at 1 40 44 pm](https://cloud.githubusercontent.com/assets/5347540/19489260/8872494c-9538-11e6-8392-7bb35f8e76b8.png)

**Comment by ChrisDart** [comment]
OK, this works for me now. I used it in a test page. We're good. Closing.
