### ISSUE TITLE
Mixed up pointers in get-started

### ISSUE THREAD

**Issue by becarpenter** [ghwood/www.ietf.org#63]
## URL
https://beta.ietf.org/about/participate/get-started/where-do-rfcs-come/

## Expected Behavior
Should point to the material from https://www.ietf.org/newcomers.html#whither

## Actual Behavior
Actually points to the material from https://www.ietf.org/newcomers.html#info
Also there seems to be no pointer correctly named for the #info material
Probably it should be https://beta.ietf.org/about/participate/get-started/resources/

A bit of a mix-up on the way into the CMS?

## Reproducing
- Browser: any
- OS: any

**Comment by ghwood** [comment]
Updated to address the issue.

https://beta.ietf.org/about/participate/get-started/
