### ISSUE TITLE
Links Entered via Wagtail Appear As Raw HTML

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#7]
## URL

https://www7.ietf.org/how-we-work/meetings/96/
## Expected Behavior

Key Details entered in Wagtail should appear as regular links under the collapsible category headings 
## Actual Behavior

Raw HTML links appear instead.  
![rawhtmlberlin96](https://cloud.githubusercontent.com/assets/21247075/18020040/37cc4268-6bad-11e6-9c39-eefa9ef3db14.png)
## Reproducing
- Browser: Firefox 48.0.2
- OS: Windows 10 Home Edition

**Comment by ghwood** [comment]
I see these as well but only for Event pages I have tested. I have raised with Torchbox in their ticketing system.

**Comment by ghwood** [comment]
This issue appears to now be fixed: https://www7.ietf.org/how-we-work/meetings/96/
