### ISSUE TITLE
Cut and Paste Produces Extraneous Syntax/Errors in Formatting

### ISSUE THREAD

**Issue by ChrisDart** [ghwood/www.ietf.org#8]
## URL

https://www7.ietf.org/how-we-work/meetings/96/faq-germany-vat-ietf-96/ (but applies to all Event sub-Pages)
## Expected Behavior

Cutting and pasting standard text from the https://www.ietf.org/meeting/96/ to migrate to a new information page should publish as displayed (standard format copying as with previous site migration).
## Actual Behavior

Extraneous syntax appears despite not appearing in the Paragraph edit.
![berlin96vat](https://cloud.githubusercontent.com/assets/21247075/18020261/8d2dd6f8-6bae-11e6-8484-2fee0a82fecd.png)
## Reproducing
- Browser: Firefox 48.0.2
- OS: Windows 10 Home Edition

**Comment by ghwood** [comment]
I tested this in Safari and Chrome on Mac OS X. Both resulted in similar, but slightly different, errors. I will raise with Torchbox in their ticketing system.

**Comment by ChrisDart** [comment]
Following up here. I worked on issue https://github.com/ietf/www.ietf.org/issues/19 since this issue was maybe fixed, and successfully managed to get rid of most of the extraneous characters except around the tables (?).  (This was done in Safari on OSX)

But when we tried to build a new page, we ran into the same problems. See here.

https://www7.ietf.org/how-we-work/meetings/past/96/ietf-test-page/

(That was done on Firefox/Windows 10.)

**Comment by ChrisDart** [comment]
Hey all,

Just letting you know, we are still getting the extraneous characters around tables.

**Comment by ChrisDart** [comment]
Extraneous characters are still occurring around all text when entered with Firefox (49.0.2).  Extraneous characters occur around tables regardless of the browser.

**Comment by ghwood** [comment]
Let's be sure discuss this during our catch up conversation today.

**Comment by ChrisDart** [comment]
Sure thing.

**Comment by ChrisDart** [comment]
Are you still in India?

**Comment by ghwood** [comment]
Chris,

A new build of the Wagtail site has been deployed on www7.ietf.org seems to fix the problem of inserting extra characters. Please take a look at the original page:

https://www7.ietf.org/how-we-work/meetings/past/96/faq-germany-vat-ietf-96/

I took a look at, some of the meeting hotel pages and they seem to reflect the fix as well.

It may be required to re-publish the page (no need to edit) for the fix to take effect on a particular page.

Please do a review of your own and let me know what you find.

-Greg

**Comment by ghwood** [comment]
This is fixed.
