### ISSUE TITLE
Preview function does not show updates

### ISSUE THREAD

**Issue by cindymorgan** [ghwood/www.ietf.org#94]
## URL

https://beta.ietf.org/admin/pages/1104/edit/

## Expected Behavior

Clicking on the Preview button should show me what the page will look like with any edits I've just made on the page.

## Actual Behavior

Clicking on the Preview button shows me something that looks just like the live page, without the edits I'd made.

## Reproducing

- Browser: Firefox 54.0.1
- OS: MacOS 10.10.5

**Comment by ghwood** [comment]
Cindy,

I'm observing this, but I also observe that--after pressing "Save draft"--the edits actually DO appear in the LIVE page even though they don't appear when pressing Preview.

Could you see if this behavior is also what you observe?

Thanks,
-Greg

**Comment by cindymorgan** [comment]
Greg,

I just checked, and I see that as well; pressing "Save Draft" makes edits to the Live page.

Thanks,
Cindy

**Comment by alexamorris** [comment]
I will confess that I've not attempted to replicate this issue but just read Cindy's post, and your response. If the "preview" button does not in fact preview the change you are considering, what is its purpose? I use the preview function in wiki edits all the time to see what a change would look like before actually saving it...and I can't honestly imagine another use. For example, as I type in this Github window now there is a Preview tab that allows me to see what this comment will look like, without having me save it. What other use does "preview" have?

**Comment by ghwood** [comment]
@alexamorris Agree.. I think there are 2 bugs: a) Save draft actually publishes the page, and b) Preview doesn't actually preview. 

I'm confident this is a bug and I've filed a ticket (noting both issues) with Torchbox.

https://projects.torchbox.com/projects/ietf/tickets/168

**Comment by ghwood** [comment]
Fixed.
