### ISSUE TITLE
No redeeming qualities of new web page for me

### ISSUE THREAD

**Issue by toerless** [ghwood/www.ietf.org#95]
## Expected Behavior

New IETF web page design is to me confusing, bloviated, annoying to maneuver.
Please figure out how to allow for the new web page to have views that emulate the existing ietf web pages. It is a lot more productive, intuitive and familiar.

**Comment by ghwood** [comment]
Not clear to how to immediately accommodate this request within the current system. Creating new views will require significant additional development. Therefore, putting this "on hold" for now.
